require "yaml"
vagrant_root = File.dirname(File.expand_path(__FILE__))

# Processar o settings.yaml e substituir variáveis de ambiente
settings_raw = File.read("#{vagrant_root}/settings.yaml")
settings_processed = settings_raw.gsub(/\$\{(\w+)\}/) { ENV[$1] || "" }
settings = YAML.load(settings_processed)

Vagrant.configure("2") do |config|
  # Specify the box
  config.vm.box = "eurolinux-vagrant/oracle-linux-9" # Replace with the box you want to use

  # Configuração da máquina virtual principal
  config.vm.define "zabbixlnx01" do |zabbixlnx01|
    zabbixlnx01.vm.hostname = "zabbixlnx01"
    zabbixlnx01.vm.network "private_network", ip: settings["network"]["control_ip"]
    zabbixlnx01.vm.network "forwarded_port", guest: 8080, host: 8080

    zabbixlnx01.vm.provider "virtualbox" do |vb|
      vb.cpus = settings["nodes"]["control"]["cpu"]
      vb.memory = settings["nodes"]["control"]["memory"]
    end

    # Desativar pasta sincronizada
    zabbixlnx01.vm.synced_folder ".", "/vagrant", disabled: true
  end
end
